# Generated by Django 3.1.5 on 2021-01-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=254)),
                ('nom', models.CharField(max_length=254)),
                ('prenoms', models.CharField(max_length=254)),
                ('tel', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(max_length=254)),
                ('type_commande', models.CharField(max_length=254)),
                ('date_commande', models.CharField(max_length=254)),
                ('date_livr_commande', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_agent_commer', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('prenoms', models.CharField(max_length=254)),
                ('adresse', models.CharField(max_length=254)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.banque')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_four', models.CharField(max_length=254)),
                ('tel_four', models.CharField(max_length=254)),
                ('adresse_four', models.CharField(max_length=254)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.banque')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=254)),
                ('prenom_client', models.CharField(max_length=254)),
                ('num_compte', models.CharField(max_length=254)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.banque')),
            ],
        ),
    ]
