# Generated by Django 3.1.5 on 2021-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_client_banque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='banque',
        ),
        migrations.AddField(
            model_name='personnel',
            name='numero_compte',
            field=models.CharField(default='NA', max_length=254),
            preserve_default=False,
        ),
    ]
