# Generated by Django 3.1.5 on 2021-01-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210131_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='numero_compte',
            new_name='num_compte',
        ),
    ]
