# Generated by Django 3.1.5 on 2021-01-31 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='poste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profil'),
            preserve_default=False,
        ),
    ]
