# Generated by Django 3.1.5 on 2021-01-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_personnel_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='poste',
            new_name='profil',
        ),
    ]
