# Generated by Django 3.1.5 on 2021-02-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210201_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.personnel'),
            preserve_default=False,
        ),
    ]
