# Generated by Django 3.1.5 on 2021-02-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_machine_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_production', models.CharField(max_length=254)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.produitfini')),
            ],
        ),
    ]
