# Generated by Django 3.1.5 on 2021-02-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='banque',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='num_compte',
            field=models.CharField(default='NA', max_length=254),
            preserve_default=False,
        ),
    ]
