# Generated by Django 3.1.5 on 2021-02-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210201_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_achat', models.CharField(max_length=254)),
                ('bois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.typematiere')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fournisseur')),
            ],
        ),
    ]
