# Generated by Django 3.1.5 on 2021-02-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210201_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='num_commande',
        ),
    ]
